# Generated by Django 4.1.3 on 2022-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='recordar',
            field=models.IntegerField(default=15),
        ),
    ]
